### ISSUE TITLE
Fly deployment missing dockerfile template

### ISSUE THREAD

**Issue by ehmatthes** [django-simple-deploy/django-simple-deploy#367]
On a configuration-only test push with editable core and pypi fly plugin, following error:

```sh
Setting ON_FLYIO secret...
Secrets are staged for the first deployment
  Set secret: ON_FLYIO=1
Setting DEBUG secret...
Secrets are staged for the first deployment
  Set secret: DEBUG=FALSE
Traceback (most recent call last):
  File "/Users/eric/projects/dsd-dev-project_vxzyr/manage.py", line 22, in <module>
    main()
  File "/Users/eric/projects/dsd-dev-project_vxzyr/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Users/eric/projects/dsd-dev-project_vxzyr/.venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/Users/eric/projects/dsd-dev-project_vxzyr/.venv/lib/python3.12/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/eric/projects/dsd-dev-project_vxzyr/.venv/lib/python3.12/site-packages/django/core/management/base.py", line 413, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/eric/projects/dsd-dev-project_vxzyr/.venv/lib/python3.12/site-packages/django/core/management/base.py", line 459, in execute
    output = self.handle(*args, **options)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eric/projects/django-simple-deploy/simple_deploy/management/commands/simple_deploy.py", line 143, in handle
    pm.hook.simple_deploy_deploy()
  File "/Users/eric/projects/dsd-dev-project_vxzyr/.venv/lib/python3.12/site-packages/pluggy/_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eric/projects/dsd-dev-project_vxzyr/.venv/lib/python3.12/site-packages/pluggy/_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eric/projects/dsd-dev-project_vxzyr/.venv/lib/python3.12/site-packages/pluggy/_callers.py", line 139, in _multicall
    raise exception.with_traceback(exception.__traceback__)
  File "/Users/eric/projects/dsd-dev-project_vxzyr/.venv/lib/python3.12/site-packages/pluggy/_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eric/projects/dsd-dev-project_vxzyr/.venv/lib/python3.12/site-packages/dsd_flyio/deploy.py", line 34, in simple_deploy_deploy
    platform_deployer.deploy()
  File "/Users/eric/projects/dsd-dev-project_vxzyr/.venv/lib/python3.12/site-packages/dsd_flyio/platform_deployer.py", line 53, in deploy
    self._add_dockerfile()
  File "/Users/eric/projects/dsd-dev-project_vxzyr/.venv/lib/python3.12/site-packages/dsd_flyio/platform_deployer.py", line 147, in _add_dockerfile
    contents = plugin_utils.get_template_string(template_path, context)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eric/projects/django-simple-deploy/simple_deploy/management/commands/utils/plugin_utils.py", line 398, in get_template_string
    template = my_engine.from_string(template_path.read_text())
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eric/.pyenv/versions/3.12.2/lib/python3.12/pathlib.py", line 1027, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/eric/.pyenv/versions/3.12.2/lib/python3.12/pathlib.py", line 1013, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/eric/projects/dsd-dev-project_vxzyr/.venv/lib/python3.12/site-packages/dsd_flyio/templates/dockerfile'
```

- [x] Troubleshoot the missing templates.
- [x] Push to PyPI
- [x] Test
- [x] Applies to other plugins?

**Comment by ehmatthes** [comment]
Fix other plugins
---

- [ ] Platform.sh, release
- [ ] Heroku, release
